services:
  db:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      TZ: Asia/Tokyo
    volumes:
      - db-storage:/var/lib/mysql

volumes:
  db-storage:
