default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: lvh.me

development:
  <<: *default
  database: rails_practice_swing_development

test:
  <<: *default
  database: rails_practice_swing_test

production:
  <<: *default
  database: rails_practice_swing_production
  username: rails_practice_swing
  password: <%= ENV["RAILS_PRACTICE_SWING_DATABASE_PASSWORD"] %>
